### ISSUE TITLE
Tag suggestion for Docker Hub project

### ISSUE THREAD

**Issue by herokang** [thelounge/docker-lounge#43] opened 2018-01-26 02:37 UTC
Hi, 
I am Kang Yin, a graduate student of Institute of Software, Chinese Academy of Sciences. Now we are doing a research on how to recommend tags for Docker Hub’s projects. We applied text mining and natural language processing to build a tag recommendation system for Docker projects.
We notice that you have created a repository on Docker Hub, which is named _thelounge/lounge_ and the project address is [https://hub.docker.com/r/thelounge/lounge/](https://hub.docker.com/r/thelounge/lounge/) 
Since the developers knows their projects better, we want to evaluate our recommendation results with your help as the project developer. We want to know if the recommended tags are reasonable for your projects. 
The following tags (ranked by order) are generated from our model automatically. Would you like to do me a favor and reply with what tags are reasonable (Good) and what are not (Bad), in form of, “Good tags: ***, ***; Bad tags: ***, ***”.

The recommend tags for your project _thelounge/lounge_ are listed as follows:

> `lounge, equivalent, cli, cli option, irc, thelounge, port mapping, available, host port, client`

It will be a great help if you can give us a feedback. 
Thank you so much for your precious time.

**Comment by astorije** [comment] 2018-01-26 06:03
Hi @herokang!
Cool project!

Personally, I would say that the only relevant tag on that is `irc`.
Maaaaaybe `cli`, but I'm not convinced. Also maybe `thelounge` though not sure because it's the name of the project, so it doesn't need to be a tag I think (could be wrong). Note that our project is getting renamed from `lounge` to `thelounge`, so `lounge` is bound to disappear.
All others are not good, like `available`, `port mapping`, etc., they don't correspond to the project at all.

I'm going to close this issue because it's not a bug report or a feature request for the project itself, but absolutely feel free to continue the discussion. Closing is just a means for us to track things, not that we want to silence the thread :)

Good luck with your project!! 🙏

**Closed** 2018-01-26 06:03 UTC
Labels: invalid
